version: '3.7'

networks:
  jenkins:

volumes:
  jenkins_home:
  jenkins_docker_certs:

services:
  docker-dind:
    image: docker:dind
    container_name: jenkins-docker
    privileged: true
    restart: always
    user: root
    networks:
      jenkins:
        aliases:
          - docker
    ports:
      - 2376:2376
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_docker_certs:/certs/client
      - ./daemon:/etc/docker
    environment:
      - DOCKER_TLS_CERTDIR=/certs
      
  jenkins:
    image: huynhtamhao/kairos-jenkins:1.0.0
    container_name: kairos-jenkins
    restart: always
    networks:
      - jenkins
    ports:
      - 18083:8080
      - 50000:50000
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - ./jenkins_docker_certs:/certs/client:ro
      - ./daemon:/etc/docker
    environment:
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/client
      - DOCKER_TLS_VERIFY=1

